name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Build artifacs
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Set up the release
        id: release
        run: |
          tag=$(cat plugin.json | grep "version*")          # Cut the line with the version in plugin.json
          tag=$(echo $tag | cut -d ":" -f 2,3)              # Split with ":" and take the version number
          tag=$(echo $tag | tr -d \"," ")                   # Trim the " and , and spaces
          echo '::set-output name=RELEASE_TAG::'$tag        # Set the environment variable

          echo '::set-output name=ARTIFACT_CORE_PATH::'$(./gradlew distributor-core:getArtifactPath -q)
          echo '::set-output name=ARTIFACT_SCRIPT_JS_PATH::'$(./gradlew distributor-js:getArtifactPath -q)

      - name: Set up the changelog
        id: changelog
        shell: bash
        run: |
          r=$(cat CHANGELOG.md)
          r="${r//'%'/'%25'}"                               # Multiline escape sequences for %
          r="${r//$'\n'/'%0A'}"                             # Multiline escape sequences for '\n'
          r="${r//$'\r'/'%0D'}"                             # Multiline escape sequences for '\r'
          echo "::set-output name=CHANGELOG::$r"

      - name: Upload distributor-core
        uses: svenstaro/upload-release-action@v2
        with:
          release_name: v${{ steps.release.outputs.RELEASE_TAG }} release
          body: ${{ steps.changelog.outputs.CHANGELOG }}

          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.release.outputs.ARTIFACT_CORE_PATH }}
          tag: v${{ steps.release.outputs.RELEASE_TAG }}

      - name: Upload distributor-js
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.release.outputs.ARTIFACT_SCRIPT_JS_PATH }}
          tag: v${{ steps.release.outputs.RELEASE_TAG }}
