name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build plugin jar
        run: ./gradlew jar

      - name: Set up the release
        id: release
        run: |
          tag=$(cat shared-plugin.json | grep "version*") # Cut the line with the version in plugin.json
          tag=$(echo $tag | cut -d ":" -f 2,3)            # Split with ":" and take the version number
          tag=$(echo $tag | tr -d \"," ")                 # Trim the " and , and spaces
          echo '::set-output name=RELEASE_TAG::'$tag      # Set the environment variable

          # Get the artifact path
          echo '::set-output name=ARTIFACT_PATH_CORE::'$(./gradlew core:getArtifactPath -q)
          echo '::set-output name=ARTIFACT_PATH_PLUGIN::'$(./gradlew plugin:getArtifactPath -q)

      - name: Upload artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.release.outputs.ARTIFACT_PATH }}
          tag: v${{ steps.release.outputs.RELEASE_TAG }}

      - name: Upload core artifact
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.build.outputs.ARTIFACT_PATH_CORE }}
          tag: v${{ steps.release.outputs.RELEASE_TAG }}

      - name: Upload plugin artifact
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.build.outputs.ARTIFACT_PATH_PLUGIN }}
          tag: v${{ steps.release.outputs.RELEASE_TAG }}
